variable "viewer_protocol_policy" {
  description = "Viewer protocol policy for CloudFront"
  type        = string
  default     = "redirect-to-https"
}

variable "min_ttl" {
  description = "Minimum TTL for CloudFront"
  type        = number
  default     = 0
}

variable "default_ttl" {
  description = "Default TTL for CloudFront"
  type        = number
  default     = 3600
}

variable "max_ttl" {
  description = "Maximum TTL for CloudFront"
  type        = number
  default     = 86400
}

variable "access_control_max_age_sec" {
  description = "Access control max age for CloudFront response headers"
  type        = number
  default     = 31536000
}

variable "include_subdomains" {
  description = "Include subdomains for CloudFront response headers"
  type        = bool
  default     = true
}

variable "preload" {
  description = "Preload for CloudFront response headers"
  type        = bool
  default     = true
}

variable "ttl" {
  description = "TTL for Route53 record"
  type        = number
  default     = 300
}

## Buckets vars
variable "buckets" {
  type = map(object({
    provision           = optional(bool, false)
    cloudfront          = optional(bool, false)
    aws_s3_access_point = optional(bool, false)
    object_ownership    = optional(string, "BucketOwnerEnforced")
    acl                 = optional(string, "private")
    lifecycle_rules = optional(object({
      prefix = optional(string, "")
      noncurrent_version_transition = optional(list(object({
        days          = string
        storage_class = string
      })), [])
      noncurrent_version_expiration = optional(object({
        days = string
      }), null)
      expiration = optional(object({
        days = string
      }), null)
      transition = optional(list(any), [])
      abort_incomplete_multipart_upload = optional(object({
        days = number
      }), null)
    }), null)
    policies = optional(set(object({
      name_sid               = string
      actions                = optional(list(string), [])
      principals_type        = optional(string, "AWS")
      principals_identifiers = optional(list(string), ["*"])
      conditions = optional(set(object({
        conditions_test     = optional(string, "StringLike")
        conditions_variable = optional(string, "aws:PrincipalArn")
        conditions_values   = optional(list(string), [])
      })), [])
    })), [])
  }))
  default = {}
}

variable "log_retention_in_days" {
  type        = string
  description = "The retention period for the CloudwatchLogs events generated by waf resource"
  default     = "365"
}

